/*
  script.js — SUPERSEDED

  This file has been split into a modular JS structure.
  See js/ directory:

    js/clock.js     — Live clock (updateClock, setInterval)
    js/sounds.js    — Audio objects + browser autoplay unlock
    js/particles.js — Particle system (updateParticles) + keyframe injection
    js/theme.js     — Theme switching, hover preview, click-to-apply, dialog chrome

  Load order matters. index.html loads them in sequence:
    clock.js → sounds.js → particles.js → theme.js

  Do not edit this file.
*/
